---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstagetest
  links:
    - url: https://youtube.com/
      title: YouTube
    - url: https://google.com/
      title: Google
  annotations:
    github.com/project-slug: wojciechtobis/backstagetest
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: wt-group